### PR TITLE
Python sir hohn

### PR DESCRIPTION
**Pull request by soenkehohn**
I had to create a new branch. Didn't work to create a pull request for my additions on the master branch. I basically only added two Python programms and some data files. The data files are not very well documented. I will think about this later. The code deals with the data, so everything about the data should become apparent from the main routine calling the data. I will think about some more improvements of the documentation later. This commit is to get my personal branch up and running.
Sönke

### CODE REVIEW

**Comment by timueh** [comment]
Thanks for making the effort.

A few remarks before merging:

- [x] Can you create a separate folder in the `python` folder? (The reason being that there are mory python implementations likely to come.)
- [x] Within that folder you created please add a `readme.md` that 
   - [x] gives a high-level idea of your code,
   - [x] presents the main results quickly, and
   - [x] also specifies the packages required to run your code, e.g. python version, `scipy`, etc... check out this [readme file of python code I just added](https://github.com/timueh/sars-cov2-modelling-initiative/tree/master/python/MiTepid_sim), which is perfect; thx @vahid-sb

**Comment by soenkehohn** [comment]
Done. I moved all previous files into a new folder. I also wrote a documentation.

**Comment by vahid-sb** [comment]
Dear @soenkehohn, thanks for sharing this. A comment and a question. Comment: the CFR you report (12% then 16%) is very high. Given the fact that many infectious people are either asymptomatic or go untested. Looking at data from Princess Diamond, which is the only population we know in which the total number of infectious is known, the CFR and mortality rates are much lower than what is normally reported. And the question: have you managed to calculate effective R0 for Bremen or Germany in different weeks since the outbreak? Similar to what these guys have done for Italy (or Lombardi): https://www.nature.com/articles/s41591-020-0883-7.pdf

**Comment by soenkehohn** [comment]
Hi,

I was also wondering about these numbers (if I understand you right). I believe that testing is relatively bad here in Bremen, so these numbers might indicate that a lot of cases remain undetected and therefore we have a strong bias towards the more severe cases. The other reason could be that the hospitals in Bremen are very fast with putting the people on ventilators.

Or what do you mean by CFR? If you mean the case fatality rate, this parameter is set to 0.0019 and later to 0.005, which is 0.19% or 0.5%. Only that in the model this parameter is multiplied with the number of active infections…


To your question… I have tried to figure out what everybody means with R0 but I don't really care. In the model the virus is spread upon contact with a fixed probability, only that contact rates are varied due to contact restrictions. So if you want you can calculate R0 from the parameters but I don't get this parameter because I don't see a direct connection to the timescale there. Therefore, I am kind of ignoring the value of R0. It doesn't play a role in the model. The model, as I see it, is rather using probabilities. 


here are the initial parameters again:

a= 0.03 # probability that the disease is transmitted upon contact
c= 4.70/P # contact rate per susceptible individual

# recovery and mortality
delta= 0.0019 # death rate of infected individuals # based on GERMAN data

rho= 0.03 # recovery rate for infected individuals

# immunity or not?
sigma= 0.0 # rate of recovered individuals that become susceptible for reinfection

**Comment by vahid-sb** [comment]
@soenkehohn, about CFR, the value you have chosen seems to be reasonable enough. And about the R0, firstly, it has a clear definition and it is very very important. It is defined as follows: "The basic reproduction number, R0, is the expected number of secondary cases produced, in a completely susceptible population, by a typical infective individual during its entire period of Infectiousness". Hence it is of utmost importance to know what is R0 for a certain disease. You can look into the following paper for more info: 
On the definition and the computation of the basic reproduction ratio {$R_0$} in models for infectious diseases in heterogeneous populations, Diekmann, Heesterbeek, and Metz, 1990, J. of Mathematical Biology.
Usually, R0 is not explicitly a parameter of the model, but something we can calculate using the parameters of the model. For example, in models based on ODEs, such as the one I use, it is the spectral radius (maximum of the absolute value of eigenvalues) of a certain matrix built from the contact rates and other parameters. 
With all that, and after looking into your repo again, it seems the parameters you have chosen, except delta, are not based on the real data. Am I right? delta is the easiest parameter to calculate. The important and difficult ones are contact rates.

**Comment by soenkehohn** [comment]
Ok, I will have a look at R0 again. Will let you know tomorrow.

All parameters are based on the data. The fact that Bremen reports the recovered cases allows to constrain all parameters of the model. Initially I started to model the development for Germany and used data where the recovered cases were not reported. That's where I realized how sensitive the model was to the parameter of the recovery rate. That is why I then looked at the Chinese data in order to constrain the recovery rate more or less. The mortality rate was already based on the data because I had reported infections and deaths, so I could constrain the mortality rate. Which still matches more or less with the data in Bremen (although the small numbers in Bremen make it statistically difficult; and, actually, the rate is slightly too large for the Bremen data). 

The infection rate is fitted to the increase of infections and since this is the product of a*c, it is actually the product of a and c that is fitted and not a or c individually. So, maybe I should write this better in the code and combine a and c to only one parameter. But at least this parameter is constrained by the data. So, to answer your question. The other parameters are all entirely based on the data!

And since these may be very specific for a certain setting, like New York or Bremen, because contact rates do not only on the number of susceptible and infected individuals but also on how many people share an entry door of a house, public transport, escalators or whatever, I would presume that the calculated R0 that can be derived from the parameters of the model is not specific to the virus itself but to the environmental surrounding that is superimposing the scenery for the virus to spread in. Therefore, I do not see the value in R0 as much as you do. But since I am coming from an ecological background where we always look at the concert of the environment and the species or communities inhabiting this environment, plus the chemistry and physics, I would not say that I am perfectly informed about the details in epidemiology.

I will look at this more closely now and will let you know what I get as R0.

Cheers,
Sönke

**Comment by soenkehohn** [comment]
I have calculated R0 from the parameters of the model now. I have updated my code at https://github.com/soenkehohn/Corona

But I also got another idea to better estimate the parameter values (including R0) from the data. I will try as soon as I can.

**Pull request merged**
